### ISSUE TITLE
Error running 'ergogen'

### ISSUE THREAD

**Issue by monlovesmango** [ceoloide/corney-island#20]
hey,

repo looks great and is really helpful! however when I try running 'ergogen' on the config.yaml I get this error:

>Error: Field "pcbs.backplate.footprints.m2_screws.what" should be one of [alps, button, choc, chocmini, diode, jstph, jumper, mx, oled, omron, pad, promicro, rgb, rotary, scrollwheel, slider, trrs, via]!

**Comment by ceoloide** [comment]
Sorry for the lack of a proper readme, and thank you for using my code!

The project leverages https://github.com/ceoloide/ergogen-footprints as a dependency for the footprints, so you need to make sure you have updated the git submodules as well before being able to run `ergogen` on this config:

```bash
git submodule update --init --recursive --remote
```

**Comment by monlovesmango** [comment]
hmm that didn't work either, and neither did moving the .js files directly into the footprints folder. somehow ergogen isn't picking up added footprints, do you know if there is something I could be doing wrong that would cause this?

**Comment by ceoloide** [comment]
Make sure you are pointing ergogen to the directory containing the `config.yaml` instead of the file itself, or it won't pick up the footprints.

In otherwords, call ergogen like this:

```bash
ergogen ergogen/
```

and not like this:

```bash
ergogen ergogen/config.yaml
```

**Comment by monlovesmango** [comment]
that did it thank you! really appreciate the responsiveness too!
